### ISSUE TITLE
Deprecated function call

### ISSUE THREAD

**Issue by aDramaQueen** [edoburu/sphinxcontrib-django#31] opened 2022-05-13 05:40 UTC
## Description
Hi,

As of Django v.4.0 there is no longer `force_text`. It's now `force_str`

[**Django - Documentation: django.utils.encoding**](https://docs.djangoproject.com/en/4.0/_modules/django/utils/encoding/)

## Steps To Reproduce
1. Create a Django 4.0 project
2. Setup Sphinx with `sphinxcontrib-django`
3. Try to generate documentation

## Actual Behavior
Throws exception during DOC generation

## Expected/Desired Behavior
Throws no exception during DOC generation

### Exception
![exception](https://user-images.githubusercontent.com/52710085/168218023-6f0db903-243e-4465-874b-52ccfb2b90c2.png)
### Deprecated Code Snippet
![force_text](https://user-images.githubusercontent.com/52710085/168217928-5021c451-5eac-4e33-a5b1-234ab5d880c7.png)

**Comment by timoludwig** [comment] 2022-09-17 22:17
@aDramaQueen this is clearly a duplicate of #24. But since this repository is apparently no longer maintained, I added support for Django 4 to my fork [nearly two years ago](https://github.com/timoludwig/sphinxcontrib-django2/commit/66703432c8b5704b5bcbeca13a3fc93fa93e19fc):

- GitHub: [timoludwig/sphinxcontrib-django2](https://github.com/timoludwig/sphinxcontrib-django2)
- PyPi: [sphinxcontrib-django2](https://pypi.org/project/sphinxcontrib-django2/)

**Comment by timoludwig** [comment] 2023-01-02 14:57
Duplicate of #24

**Closed by timoludwig** 2023-01-02 14:57 UTC
